name: Go
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .
  
  test:
    name: Unit test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest]
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Unit test
        run: go test ./...
      
      - name: Component test
        run:  
          go install ./... |
          cd test |
          ls -al |
          sh ./run_all.sh
